version: "3.8"
services:
  postgres:
    container_name: "perfume-shop_db"
    image: "postgres:16-alpine"
    restart: always
    environment:
      - POSTGRES_USER=perfume-shop
      - POSTGRES_PASSWORD=perfume-shop
      - POSTGRES_DB=perfume-shop
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
